<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $passengers = DB::table('passengers')->orderBy('id')->get();
        $drivers = DB::table('drivers')->orderBy('id')->get();
        $tariffs = DB::table('tariffs')->get();

        $orders = [
            [
                'order_number' => 'ТК-4821',
                'passenger_id' => $passengers[0]->id ?? 1,
                'driver_id' => null,
                'tariff_id' => $tariffs->where('code', 'business')->first()->id ?? 3,
                'status' => 'new',
                'pickup_address' => 'ул. Ленина, 15',
                'pickup_lat' => 55.7558,
                'pickup_lng' => 37.6173,
                'dropoff_address' => 'Аэропорт Домодедово',
                'dropoff_lat' => 55.4146,
                'dropoff_lng' => 37.9003,
                'distance' => 42,
                'duration' => 55,
                'final_price' => 1850,
                'base_price' => 1850,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'pending',
                'driver_earnings' => null,
                'commission_amount' => null,
                'passenger_name' => 'Иванов А.С.',
                'passenger_phone' => '+79000000100',
                'notes' => 'Багаж: 2 чемодана',
                'accepted_at' => null,
                'started_at' => null,
                'completed_at' => null,
                'created_at' => DB::raw("DATEADD(minute, -15, GETDATE())"),
                'updated_at' => DB::raw('GETDATE()'),
            ],
            [
                'order_number' => 'ТК-4820',
                'passenger_id' => $passengers[1]->id ?? 2,
                'driver_id' => null,
                'tariff_id' => $tariffs->where('code', 'comfort')->first()->id ?? 2,
                'status' => 'new',
                'pickup_address' => 'ул. Профсоюзная, 92',
                'pickup_lat' => 55.6415,
                'pickup_lng' => 37.5252,
                'dropoff_address' => 'Центральный парк',
                'dropoff_lat' => 55.7580,
                'dropoff_lng' => 37.6210,
                'distance' => 15,
                'duration' => 28,
                'final_price' => 680,
                'base_price' => 680,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'pending',
                'driver_earnings' => null,
                'commission_amount' => null,
                'passenger_name' => 'Петрова Е.И.',
                'passenger_phone' => '+79000000101',
                'notes' => null,
                'accepted_at' => null,
                'started_at' => null,
                'completed_at' => null,
                'created_at' => DB::raw("DATEADD(minute, -30, GETDATE())"),
                'updated_at' => DB::raw('GETDATE()'),
            ],
            [
                'order_number' => 'ТК-4819',
                'passenger_id' => $passengers[2]->id ?? 3,
                'driver_id' => null,
                'tariff_id' => $tariffs->where('code', 'economy')->first()->id ?? 1,
                'status' => 'new',
                'pickup_address' => 'пр. Мира, 45',
                'pickup_lat' => 55.7815,
                'pickup_lng' => 37.6345,
                'dropoff_address' => 'ВДНХ',
                'dropoff_lat' => 55.8297,
                'dropoff_lng' => 37.6388,
                'distance' => 8,
                'duration' => 18,
                'final_price' => 320,
                'base_price' => 320,
                'surge_multiplier' => 1.0,
                'payment_method' => 'cash',
                'payment_status' => 'pending',
                'driver_earnings' => null,
                'commission_amount' => null,
                'passenger_name' => 'Сидоров В.П.',
                'passenger_phone' => '+79000000102',
                'notes' => null,
                'accepted_at' => null,
                'started_at' => null,
                'completed_at' => null,
                'created_at' => DB::raw("DATEADD(minute, -45, GETDATE())"),
                'updated_at' => DB::raw('GETDATE()'),
            ],
            [
                'order_number' => 'ТК-4818',
                'passenger_id' => $passengers[3]->id ?? 4,
                'driver_id' => $drivers[2]->id ?? 3,
                'tariff_id' => $tariffs->where('code', 'business')->first()->id ?? 3,
                'status' => 'completed',
                'pickup_address' => 'Таганская площадь',
                'pickup_lat' => 55.7425,
                'pickup_lng' => 37.6531,
                'dropoff_address' => 'Сколково',
                'dropoff_lat' => 55.7325,
                'dropoff_lng' => 37.4262,
                'distance' => 38,
                'duration' => 48,
                'final_price' => 2100,
                'base_price' => 2100,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'paid',
                'driver_earnings' => 1680,
                'commission_amount' => 420,
                'passenger_name' => 'Михайлов А.Д.',
                'passenger_phone' => '+79000000103',
                'notes' => 'Багаж: 1 чемодан',
                'accepted_at' => DB::raw("DATEADD(hour, -2, GETDATE())"),
                'started_at' => DB::raw("DATEADD(minute, -110, GETDATE())"),
                'completed_at' => DB::raw("DATEADD(hour, -1, GETDATE())"),
                'created_at' => DB::raw("DATEADD(hour, -3, GETDATE())"),
                'updated_at' => DB::raw("DATEADD(hour, -1, GETDATE())"),
            ],
            [
                'order_number' => 'ТК-4817',
                'passenger_id' => $passengers[4]->id ?? 5,
                'driver_id' => $drivers[0]->id ?? 1,
                'tariff_id' => $tariffs->where('code', 'comfort')->first()->id ?? 2,
                'status' => 'completed',
                'pickup_address' => 'ул. Арбат, 10',
                'pickup_lat' => 55.7520,
                'pickup_lng' => 37.5874,
                'dropoff_address' => 'Ленинградский пр-т, 37',
                'dropoff_lat' => 55.7915,
                'dropoff_lng' => 37.5405,
                'distance' => 12,
                'duration' => 25,
                'final_price' => 550,
                'base_price' => 550,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'paid',
                'driver_earnings' => 440,
                'commission_amount' => 110,
                'passenger_name' => 'Соколова М.В.',
                'passenger_phone' => '+79000000104',
                'notes' => null,
                'accepted_at' => DB::raw("DATEADD(hour, -4, GETDATE())"),
                'started_at' => DB::raw("DATEADD(minute, -230, GETDATE())"),
                'completed_at' => DB::raw("DATEADD(minute, -200, GETDATE())"),
                'created_at' => DB::raw("DATEADD(hour, -5, GETDATE())"),
                'updated_at' => DB::raw("DATEADD(minute, -200, GETDATE())"),
            ],
        ];
            [
                'order_number' => 'ТК-4819',
                'passenger_id' => $passengers[2]->id ?? 3,
                'driver_id' => $drivers[1]->id ?? 2,
                'tariff_id' => $tariffs->where('code', 'economy')->first()->id ?? 1,
                'status' => 'in_progress',
                'pickup_address' => 'пр. Мира, 45',
                'pickup_lat' => 55.7815,
                'pickup_lng' => 37.6345,
                'dropoff_address' => 'ВДНХ',
                'dropoff_lat' => 55.8297,
                'dropoff_lng' => 37.6388,
                'distance' => 8,
                'duration' => 18,
                'final_price' => 320,
                'base_price' => 320,
                'surge_multiplier' => 1.0,
                'payment_method' => 'cash',
                'payment_status' => 'pending',
                'driver_earnings' => null,
                'commission_amount' => null,
                'passenger_name' => 'Сидоров В.П.',
                'passenger_phone' => '+79000000102',
                'notes' => null,
                'accepted_at' => DB::raw("DATEADD(minute, -20, GETDATE())"),
                'started_at' => DB::raw("DATEADD(minute, -10, GETDATE())"),
                'completed_at' => null,
                'created_at' => DB::raw("DATEADD(minute, -45, GETDATE())"),
                'updated_at' => DB::raw('GETDATE()'),
            ],
            [
                'order_number' => 'ТК-4818',
                'passenger_id' => $passengers[3]->id ?? 4,
                'driver_id' => $drivers[2]->id ?? 3,
                'tariff_id' => $tariffs->where('code', 'business')->first()->id ?? 3,
                'status' => 'completed',
                'pickup_address' => 'Таганская площадь',
                'pickup_lat' => 55.7425,
                'pickup_lng' => 37.6531,
                'dropoff_address' => 'Сколково',
                'dropoff_lat' => 55.7325,
                'dropoff_lng' => 37.4262,
                'distance' => 38,
                'duration' => 48,
                'final_price' => 2100,
                'base_price' => 2100,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'paid',
                'driver_earnings' => 1680,
                'commission_amount' => 420,
                'passenger_name' => 'Михайлов А.Д.',
                'passenger_phone' => '+79000000103',
                'notes' => 'Багаж: 1 чемодан',
                'accepted_at' => DB::raw("DATEADD(hour, -2, GETDATE())"),
                'started_at' => DB::raw("DATEADD(minute, -110, GETDATE())"),
                'completed_at' => DB::raw("DATEADD(hour, -1, GETDATE())"),
                'created_at' => DB::raw("DATEADD(hour, -3, GETDATE())"),
                'updated_at' => DB::raw("DATEADD(hour, -1, GETDATE())"),
            ],
            [
                'order_number' => 'ТК-4817',
                'passenger_id' => $passengers[4]->id ?? 5,
                'driver_id' => $drivers[0]->id ?? 1,
                'tariff_id' => $tariffs->where('code', 'comfort')->first()->id ?? 2,
                'status' => 'completed',
                'pickup_address' => 'ул. Арбат, 10',
                'pickup_lat' => 55.7520,
                'pickup_lng' => 37.5874,
                'dropoff_address' => 'Ленинградский пр-т, 37',
                'dropoff_lat' => 55.7915,
                'dropoff_lng' => 37.5405,
                'distance' => 12,
                'duration' => 25,
                'final_price' => 550,
                'base_price' => 550,
                'surge_multiplier' => 1.0,
                'payment_method' => 'card',
                'payment_status' => 'paid',
                'driver_earnings' => 440,
                'commission_amount' => 110,
                'passenger_name' => 'Соколова М.В.',
                'passenger_phone' => '+79000000104',
                'notes' => null,
                'accepted_at' => DB::raw("DATEADD(hour, -4, GETDATE())"),
                'started_at' => DB::raw("DATEADD(minute, -230, GETDATE())"),
                'completed_at' => DB::raw("DATEADD(minute, -200, GETDATE())"),
                'created_at' => DB::raw("DATEADD(hour, -5, GETDATE())"),
                'updated_at' => DB::raw("DATEADD(minute, -200, GETDATE())"),
            ],
        ];

        DB::table('orders')->insert($orders);
    }
}
